package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogOrder<M extends BaseLogOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setTeamName(java.lang.String teamName) {
		set("team_name", teamName);
	}

	public java.lang.String getTeamName() {
		return get("team_name");
	}

	public void setSerialNum(java.lang.String serialNum) {
		set("serial_num", serialNum);
	}

	public java.lang.String getSerialNum() {
		return get("serial_num");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setCurrency(java.lang.String currency) {
		set("currency", currency);
	}

	public java.lang.String getCurrency() {
		return get("currency");
	}

	public void setPrice(java.lang.Integer price) {
		set("price", price);
	}

	public java.lang.Integer getPrice() {
		return get("price");
	}

	public void setIsProduct(java.lang.String isProduct) {
		set("is_product", isProduct);
	}

	public java.lang.String getIsProduct() {
		return get("is_product");
	}

	public void setGoodsId(java.lang.String goodsId) {
		set("goods_id", goodsId);
	}

	public java.lang.String getGoodsId() {
		return get("goods_id");
	}

	public void setGoodsNum(java.lang.Integer goodsNum) {
		set("goods_num", goodsNum);
	}

	public java.lang.Integer getGoodsNum() {
		return get("goods_num");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setIosPayPoint(java.lang.String iosPayPoint) {
		set("ios_pay_point", iosPayPoint);
	}

	public java.lang.String getIosPayPoint() {
		return get("ios_pay_point");
	}

	public void setAndroidPayPoint(java.lang.String androidPayPoint) {
		set("android_pay_point", androidPayPoint);
	}

	public java.lang.String getAndroidPayPoint() {
		return get("android_pay_point");
	}

	public void setOpenudid(java.lang.String openudid) {
		set("openudid", openudid);
	}

	public java.lang.String getOpenudid() {
		return get("openudid");
	}

	public void setImei(java.lang.String imei) {
		set("imei", imei);
	}

	public java.lang.String getImei() {
		return get("imei");
	}

	public void setModel(java.lang.String model) {
		set("model", model);
	}

	public java.lang.String getModel() {
		return get("model");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}

	public java.lang.String getOs() {
		return get("os");
	}

	public void setOsVersion(java.lang.String osVersion) {
		set("os_version", osVersion);
	}

	public java.lang.String getOsVersion() {
		return get("os_version");
	}

	public void setResolution(java.lang.String resolution) {
		set("resolution", resolution);
	}

	public java.lang.String getResolution() {
		return get("resolution");
	}

	public void setChId(java.lang.Integer chId) {
		set("ch_id", chId);
	}

	public java.lang.Integer getChId() {
		return get("ch_id");
	}

	public void setCarrier(java.lang.String carrier) {
		set("carrier", carrier);
	}

	public java.lang.String getCarrier() {
		return get("carrier");
	}

	public void setNet(java.lang.String net) {
		set("net", net);
	}

	public java.lang.String getNet() {
		return get("net");
	}

	public void setNetConnected(java.lang.String netConnected) {
		set("net_connected", netConnected);
	}

	public java.lang.String getNetConnected() {
		return get("net_connected");
	}

	public void setPakVersion(java.lang.String pakVersion) {
		set("pak_version", pakVersion);
	}

	public java.lang.String getPakVersion() {
		return get("pak_version");
	}

	public void setPackageName(java.lang.String packageName) {
		set("package_name", packageName);
	}

	public java.lang.String getPackageName() {
		return get("package_name");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}

	public java.lang.String getCountry() {
		return get("country");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

}
