package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRetainUser<M extends BaseRetainUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setAddUser(java.lang.Integer addUser) {
		set("add_user", addUser);
	}

	public java.lang.Integer getAddUser() {
		return get("add_user");
	}

	public void setNextDayRetain(java.lang.Integer nextDayRetain) {
		set("next_day_retain", nextDayRetain);
	}

	public java.lang.Integer getNextDayRetain() {
		return get("next_day_retain");
	}

	public void setSevenDayRetain(java.lang.Integer sevenDayRetain) {
		set("seven_day_retain", sevenDayRetain);
	}

	public java.lang.Integer getSevenDayRetain() {
		return get("seven_day_retain");
	}

	public void setMonthRetain(java.lang.Integer monthRetain) {
		set("month_retain", monthRetain);
	}

	public java.lang.Integer getMonthRetain() {
		return get("month_retain");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}

	public java.lang.String getOs() {
		return get("os");
	}

}
