package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLossUser<M extends BaseLossUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public void setFirstDay(java.lang.Integer firstDay) {
		set("first_day", firstDay);
	}

	public java.lang.Integer getFirstDay() {
		return get("first_day");
	}

	public void setSecondDay(java.lang.Integer secondDay) {
		set("second_day", secondDay);
	}

	public java.lang.Integer getSecondDay() {
		return get("second_day");
	}

	public void setThirdDay(java.lang.Integer thirdDay) {
		set("third_day", thirdDay);
	}

	public java.lang.Integer getThirdDay() {
		return get("third_day");
	}

	public void setForthDay(java.lang.Integer forthDay) {
		set("forth_day", forthDay);
	}

	public java.lang.Integer getForthDay() {
		return get("forth_day");
	}

	public void setFifthDay(java.lang.Integer fifthDay) {
		set("fifth_day", fifthDay);
	}

	public java.lang.Integer getFifthDay() {
		return get("fifth_day");
	}

	public void setSixthDay(java.lang.Integer sixthDay) {
		set("sixth_day", sixthDay);
	}

	public java.lang.Integer getSixthDay() {
		return get("sixth_day");
	}

	public void setSevenDay(java.lang.Integer sevenDay) {
		set("seven_day", sevenDay);
	}

	public java.lang.Integer getSevenDay() {
		return get("seven_day");
	}

	public void setEighthDay(java.lang.Integer eighthDay) {
		set("eighth_day", eighthDay);
	}

	public java.lang.Integer getEighthDay() {
		return get("eighth_day");
	}

	public void setNinthDay(java.lang.Integer ninthDay) {
		set("ninth_day", ninthDay);
	}

	public java.lang.Integer getNinthDay() {
		return get("ninth_day");
	}

	public void setTenthDay(java.lang.Integer tenthDay) {
		set("tenth_day", tenthDay);
	}

	public java.lang.Integer getTenthDay() {
		return get("tenth_day");
	}

	public void setEleventhDay(java.lang.Integer eleventhDay) {
		set("eleventh_day", eleventhDay);
	}

	public java.lang.Integer getEleventhDay() {
		return get("eleventh_day");
	}

	public void setTwelfthDay(java.lang.Integer twelfthDay) {
		set("twelfth_day", twelfthDay);
	}

	public java.lang.Integer getTwelfthDay() {
		return get("twelfth_day");
	}

	public void setThirteenthDay(java.lang.Integer thirteenthDay) {
		set("thirteenth_day", thirteenthDay);
	}

	public java.lang.Integer getThirteenthDay() {
		return get("thirteenth_day");
	}

	public void setFourteenthDay(java.lang.Integer fourteenthDay) {
		set("fourteenth_day", fourteenthDay);
	}

	public java.lang.Integer getFourteenthDay() {
		return get("fourteenth_day");
	}

	public void setThirtyDay(java.lang.Integer thirtyDay) {
		set("thirty_day", thirtyDay);
	}

	public java.lang.Integer getThirtyDay() {
		return get("thirty_day");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}

	public java.lang.String getOs() {
		return get("os");
	}

}
