package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogout<M extends BaseLogout<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setInternalId(java.lang.String internalId) {
		set("internal_id", internalId);
	}

	public java.lang.String getInternalId() {
		return get("internal_id");
	}

	public void setArenaWinTimes(java.lang.Integer arenaWinTimes) {
		set("arena_win_times", arenaWinTimes);
	}

	public java.lang.Integer getArenaWinTimes() {
		return get("arena_win_times");
	}

	public void setArenaTieTimes(java.lang.Integer arenaTieTimes) {
		set("arena_tie_times", arenaTieTimes);
	}

	public java.lang.Integer getArenaTieTimes() {
		return get("arena_tie_times");
	}

	public void setArenaLoseTimes(java.lang.Integer arenaLoseTimes) {
		set("arena_lose_times", arenaLoseTimes);
	}

	public java.lang.Integer getArenaLoseTimes() {
		return get("arena_lose_times");
	}

	public void setOnlineTime(java.lang.Integer onlineTime) {
		set("online_time", onlineTime);
	}

	public java.lang.Integer getOnlineTime() {
		return get("online_time");
	}

	public void setLogoutTime(java.util.Date logoutTime) {
		set("logout_time", logoutTime);
	}

	public java.util.Date getLogoutTime() {
		return get("logout_time");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

}
