package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRetainEquipment<M extends BaseRetainEquipment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setAddEquipment(java.lang.Integer addEquipment) {
		set("add_equipment", addEquipment);
	}

	public java.lang.Integer getAddEquipment() {
		return get("add_equipment");
	}

	public void setFirstDay(java.lang.Integer firstDay) {
		set("first_day", firstDay);
	}

	public java.lang.Integer getFirstDay() {
		return get("first_day");
	}

	public void setSecondDay(java.lang.Integer secondDay) {
		set("second_day", secondDay);
	}

	public java.lang.Integer getSecondDay() {
		return get("second_day");
	}

	public void setThirdDay(java.lang.Integer thirdDay) {
		set("third_day", thirdDay);
	}

	public java.lang.Integer getThirdDay() {
		return get("third_day");
	}

	public void setForthDay(java.lang.Integer forthDay) {
		set("forth_day", forthDay);
	}

	public java.lang.Integer getForthDay() {
		return get("forth_day");
	}

	public void setFifthDay(java.lang.Integer fifthDay) {
		set("fifth_day", fifthDay);
	}

	public java.lang.Integer getFifthDay() {
		return get("fifth_day");
	}

	public void setSixthDay(java.lang.Integer sixthDay) {
		set("sixth_day", sixthDay);
	}

	public java.lang.Integer getSixthDay() {
		return get("sixth_day");
	}

	public void setSevenDay(java.lang.Integer sevenDay) {
		set("seven_day", sevenDay);
	}

	public java.lang.Integer getSevenDay() {
		return get("seven_day");
	}

	public void setFourteenDay(java.lang.Integer fourteenDay) {
		set("fourteen_day", fourteenDay);
	}

	public java.lang.Integer getFourteenDay() {
		return get("fourteen_day");
	}

	public void setThirtyDay(java.lang.Integer thirtyDay) {
		set("thirty_day", thirtyDay);
	}

	public java.lang.Integer getThirtyDay() {
		return get("thirty_day");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}

	public java.lang.String getOs() {
		return get("os");
	}

}
