package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGuideStep<M extends BaseGuideStep<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setMainId(java.lang.Integer mainId) {
		set("main_id", mainId);
	}

	public java.lang.Integer getMainId() {
		return get("main_id");
	}

	public void setSubId(java.lang.Integer subId) {
		set("sub_id", subId);
	}

	public java.lang.Integer getSubId() {
		return get("sub_id");
	}

	public void setTimestamp(java.util.Date timestamp) {
		set("timestamp", timestamp);
	}

	public java.util.Date getTimestamp() {
		return get("timestamp");
	}

}
