package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLossUser<M extends BaseLossUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return get("num");
	}

	public void setSevenDay(java.lang.Integer sevenDay) {
		set("seven_day", sevenDay);
	}

	public java.lang.Integer getSevenDay() {
		return get("seven_day");
	}

	public void setForteenDay(java.lang.Integer forteenDay) {
		set("forteen_day", forteenDay);
	}

	public java.lang.Integer getForteenDay() {
		return get("forteen_day");
	}

	public void setThirtyDay(java.lang.Integer thirtyDay) {
		set("thirty_day", thirtyDay);
	}

	public java.lang.Integer getThirtyDay() {
		return get("thirty_day");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}

	public java.lang.String getOs() {
		return get("os");
	}

}
