package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogCharge<M extends BaseLogCharge<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setTeamName(java.lang.String teamName) {
		set("team_name", teamName);
	}

	public java.lang.String getTeamName() {
		return get("team_name");
	}

	public void setCurrency(java.lang.String currency) {
		set("currency", currency);
	}

	public java.lang.String getCurrency() {
		return get("currency");
	}

	public void setCount(java.lang.Double count) {
		set("count", count);
	}

	public java.lang.Double getCount() {
		return get("count");
	}

	public void setTimestamp(java.util.Date timestamp) {
		set("timestamp", timestamp);
	}

	public java.util.Date getTimestamp() {
		return get("timestamp");
	}

}
