package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseActiveUser<M extends BaseActiveUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setDau(java.lang.Integer dau) {
		set("dau", dau);
	}

	public java.lang.Integer getDau() {
		return get("dau");
	}

	public void setWau(java.lang.Integer wau) {
		set("wau", wau);
	}

	public java.lang.Integer getWau() {
		return get("wau");
	}

	public void setMau(java.lang.Integer mau) {
		set("mau", mau);
	}

	public java.lang.Integer getMau() {
		return get("mau");
	}

}
