package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogRmb<M extends BaseLogRmb<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setGetOrConsume(java.lang.Integer getOrConsume) {
		set("get_or_consume", getOrConsume);
	}

	public java.lang.Integer getGetOrConsume() {
		return get("get_or_consume");
	}

	public void setReason(java.lang.String reason) {
		set("reason", reason);
	}

	public java.lang.String getReason() {
		return get("reason");
	}

	public void setTimestamp(java.util.Date timestamp) {
		set("timestamp", timestamp);
	}

	public java.util.Date getTimestamp() {
		return get("timestamp");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

}
