package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOnlineCount<M extends BaseOnlineCount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setOnlineCount(java.lang.Integer onlineCount) {
		set("online_count", onlineCount);
	}

	public java.lang.Integer getOnlineCount() {
		return get("online_count");
	}

	public void setOnlineDatetime(java.util.Date onlineDatetime) {
		set("online_datetime", onlineDatetime);
	}

	public java.util.Date getOnlineDatetime() {
		return get("online_datetime");
	}

	public void setOnlineDate(java.util.Date onlineDate) {
		set("online_date", onlineDate);
	}

	public java.util.Date getOnlineDate() {
		return get("online_date");
	}

}
