package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClientViewHeroMp4<M extends BaseClientViewHeroMp4<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setHeroId(java.lang.String heroId) {
		set("hero_id", heroId);
	}

	public java.lang.String getHeroId() {
		return get("hero_id");
	}

	public void setAccount(java.lang.String account) {
		set("account", account);
	}

	public java.lang.String getAccount() {
		return get("account");
	}

	public void setLevel(java.lang.Integer level) {
		set("level", level);
	}

	public java.lang.Integer getLevel() {
		return get("level");
	}

	public void setViewSource(java.lang.String viewSource) {
		set("view_source", viewSource);
	}

	public java.lang.String getViewSource() {
		return get("view_source");
	}

	public void setDt(java.util.Date dt) {
		set("dt", dt);
	}

	public java.util.Date getDt() {
		return get("dt");
	}

}
