package common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("create_role", "account", CreateRole.class);
		arp.addMapping("device_info", "openudid", DeviceInfo.class);
		arp.addMapping("login", "id", Login.class);
		arp.addMapping("logout", "id", Logout.class);
	}
}

