package common.model;

import common.model.base.BaseActiveUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ActiveUser extends BaseActiveUser<ActiveUser> {
	public static final ActiveUser dao = new ActiveUser();
}
