package common.model;

import common.model.base.BaseArenaRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArenaRecord extends BaseArenaRecord<ArenaRecord> {
	public static final ArenaRecord dao = new ArenaRecord();
}
