package common.model;

import common.model.base.BaseClientViewHeroMp4;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClientViewHeroMp4 extends BaseClientViewHeroMp4<ClientViewHeroMp4> {
	public static final ClientViewHeroMp4 dao = new ClientViewHeroMp4();
}
