package common.model;

import common.model.base.BaseCreateRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CreateRole extends BaseCreateRole<CreateRole> {
	public static final CreateRole dao = new CreateRole();
}
