package common.model;

import common.model.base.BaseDeviceInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeviceInfo extends BaseDeviceInfo<DeviceInfo> {
	public static final DeviceInfo dao = new DeviceInfo();
}
