package common.model;

import common.model.base.BaseGmRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GmRecord extends BaseGmRecord<GmRecord> {
	public static final GmRecord dao = new GmRecord();
}
