package common.model;

import common.model.base.BaseGuideStep;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GuideStep extends BaseGuideStep<GuideStep> {
	public static final GuideStep dao = new GuideStep();
}
