package common.model;

import common.model.base.BaseLadderRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LadderRecord extends BaseLadderRecord<LadderRecord> {
	public static final LadderRecord dao = new LadderRecord();
}
