package common.model;

import common.model.base.BaseLevelUp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LevelUp extends BaseLevelUp<LevelUp> {
	public static final LevelUp dao = new LevelUp();
}
