package common.model;

import common.model.base.BaseLogCharge;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogCharge extends BaseLogCharge<LogCharge> {
	public static final LogCharge dao = new LogCharge();
}
