package common.model;

import common.model.base.BaseLogGold;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogGold extends BaseLogGold<LogGold> {
	public static final LogGold dao = new LogGold();
}
