package common.model;

import common.model.base.BaseLogOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogOrder extends BaseLogOrder<LogOrder> {
	public static final LogOrder dao = new LogOrder();
}
