package common.model;

import common.model.base.BaseLogObj;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogObj extends BaseLogObj<LogObj> {
	public static final LogObj dao = new LogObj();
}
