package common.model;

import common.model.base.BaseLogout;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Logout extends BaseLogout<Logout> {
	public static final Logout dao = new Logout();
}
