package common.model;

import common.model.base.BaseLogRmb;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogRmb extends BaseLogRmb<LogRmb> {
	public static final LogRmb dao = new LogRmb();
}
