package common.model;

import common.model.base.BaseLossUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LossUser extends BaseLossUser<LossUser> {
	public static final LossUser dao = new LossUser();
}
