package common.model;

import common.model.base.BaseOnlineCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OnlineCount extends BaseOnlineCount<OnlineCount> {
	public static final OnlineCount dao = new OnlineCount();
}
