package common.model;

import common.model.base.BasePaymentDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaymentDetail extends BasePaymentDetail<PaymentDetail> {
	public static final PaymentDetail dao = new PaymentDetail();
}
