package common.model;

import common.model.base.BaseRetainUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RetainUser extends BaseRetainUser<RetainUser> {
	public static final RetainUser dao = new RetainUser();
}
