package common.model;

import common.model.base.BaseRetainEquipment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RetainEquipment extends BaseRetainEquipment<RetainEquipment> {
	public static final RetainEquipment dao = new RetainEquipment();
}
