package common.model;

import common.model.base.BaseReturnUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnUser extends BaseReturnUser<ReturnUser> {
	public static final ReturnUser dao = new ReturnUser();
}
