package common.model;

import common.model.base.BaseReturnUserCopy1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnUserCopy1 extends BaseReturnUserCopy1<ReturnUserCopy1> {
	public static final ReturnUserCopy1 dao = new ReturnUserCopy1();
}
