package common.model;

import common.model.base.BaseReturnUserCopy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReturnUserCopy extends BaseReturnUserCopy<ReturnUserCopy> {
	public static final ReturnUserCopy dao = new ReturnUserCopy();
}
