package common.model;

import common.model.base.BaseSecRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecRole extends BaseSecRole<SecRole> {
	public static final SecRole dao = new SecRole();
}
