package common.model;

import common.model.base.BaseSecUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecUser extends BaseSecUser<SecUser> {
	public static final SecUser dao = new SecUser();
}
