package common.model;

import common.model.base.BaseSecUserRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecUserRole extends BaseSecUserRole<SecUserRole> {
	public static final SecUserRole dao = new SecUserRole();
}
