package common.model;

import common.model.base.BaseUserFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserFeedback extends BaseUserFeedback<UserFeedback> {
	public static final UserFeedback dao = new UserFeedback();
}
